CREATE DATABASE Keriswatch;

CREATE TABLE Users (
	id INT PRIMARY KEY IDENTITY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(30) NOT NULL CHECK (role IN ('Organisation', 'Admin', 'NormalUser'))
);

CREATE TABLE Admin (
	id INT PRIMARY KEY IDENTITY,
	username VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(id),
	password VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(password),
	email VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(email)
);

CREATE TABLE Organisation ( 
	id INT PRIMARY KEY IDENTITY,
	username VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(id),	
	password VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(password),	
	email VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(email),
	orgNumber INT NOT NULL UNIQUE, /* ignoring the international code (+65), can? */
);

CREATE TABLE NormalUser (
	id INT PRIMARY KEY IDENTITY,
	username VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(id),	
	password VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(password),
	email VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(email)
);